import { test, expect } from '@playwright/test';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Configuration extraction script for InstantDB
 * This script navigates InstantDB docs and extracts configuration information
 */

test.describe('InstantDB Configuration Extraction', () => {
  test('extract API endpoints and configuration', async ({ page }) => {
    const config = {
      appId: '588227b6-6022-44a9-88f3-b1c2e2cce304',
      baseUrl: 'https://api.instantdb.com',
      endpoints: {},
      auth: {},
    };

    // Navigate to InstantDB docs
    await page.goto('https://www.instantdb.com/docs');
    await page.waitForLoadState('networkidle');

    // Try to find API endpoint information
    const content = await page.content();
    
    // Extract any API endpoint patterns
    const apiPatterns = content.match(/api[^"'\s]*instantdb[^"'\s]*/gi) || [];
    const endpointPatterns = content.match(/\/[a-z]+\/[a-z]+/gi) || [];
    
    console.log('Found API patterns:', apiPatterns);
    console.log('Found endpoint patterns:', endpointPatterns);

    // Navigate to auth docs
    try {
      await page.goto('https://www.instantdb.com/docs/auth');
      await page.waitForLoadState('networkidle');
      
      const authContent = await page.textContent('body');
      console.log('Auth docs content preview:', authContent?.substring(0, 500));
      
      // Look for Google OAuth configuration
      if (authContent?.includes('Google') || authContent?.includes('OAuth')) {
        config.auth.googleOAuth = {
          enabled: true,
          note: 'Google OAuth configuration found in docs',
        };
      }
    } catch (error) {
      console.log('Could not access auth docs:', error.message);
    }

    // Navigate to HTTP API docs
    try {
      await page.goto('https://www.instantdb.com/docs/http-api');
      await page.waitForLoadState('networkidle');
      
      const apiContent = await page.textContent('body');
      console.log('HTTP API docs content preview:', apiContent?.substring(0, 500));
      
      // Extract endpoint information
      const endpointMatches = apiContent?.match(/\/[a-z-]+\/[a-z-]+/gi) || [];
      config.endpoints.discovered = [...new Set(endpointMatches)];
    } catch (error) {
      console.log('Could not access HTTP API docs:', error.message);
    }

    // Save configuration
    const configPath = path.join(__dirname, '../instantdb-config.json');
    fs.writeFileSync(configPath, JSON.stringify(config, null, 2));
    console.log('Configuration saved to:', configPath);

    expect(config.appId).toBeDefined();
  });

  test('create Flutter configuration file', async ({ page }) => {
    const flutterConfig = {
      instantDB: {
        appId: '588227b6-6022-44a9-88f3-b1c2e2cce304',
        baseUrl: 'https://api.instantdb.com',
        // Note: InstantDB uses WebSocket transactions, not REST API
        // For Flutter, you need a backend proxy or use InstantDB Admin HTTP API
        useBackendProxy: true,
        backendUrl: process.env.BACKEND_URL || 'http://localhost:3000',
      },
      auth: {
        emailPassword: {
          enabled: true,
          // Password hashing should be done server-side
          hashOnServer: true,
        },
        googleOAuth: {
          enabled: true,
          // Configure in InstantDB dashboard
          clientId: process.env.GOOGLE_CLIENT_ID || '',
          redirectUri: process.env.GOOGLE_REDIRECT_URI || '',
        },
      },
      endpoints: {
        // These are example endpoints - verify with InstantDB docs
        createUser: '/api/users/create',
        findUser: '/api/users/find',
        saveRecipe: '/api/recipes/save',
        getRecipes: '/api/recipes/get',
      },
    };

    const configPath = path.join(__dirname, '../chefli_flutter/lib/config/instantdb_config.dart');
    const configDir = path.dirname(configPath);
    
    // Create directory if it doesn't exist
    if (!fs.existsSync(configDir)) {
      fs.mkdirSync(configDir, { recursive: true });
    }

    // Generate Dart configuration file
    const dartConfig = `// InstantDB Configuration
// Auto-generated by Playwright configuration script
// Update these values based on your InstantDB setup

class InstantDBConfig {
  static const String appId = '${flutterConfig.instantDB.appId}';
  static const String baseUrl = '${flutterConfig.instantDB.baseUrl}';
  static const bool useBackendProxy = ${flutterConfig.instantDB.useBackendProxy};
  static const String backendUrl = '${flutterConfig.instantDB.backendUrl}';
  
  // Auth Configuration
  static const bool emailPasswordEnabled = ${flutterConfig.auth.emailPassword.enabled};
  static const bool hashPasswordOnServer = ${flutterConfig.auth.emailPassword.hashOnServer};
  static const bool googleOAuthEnabled = ${flutterConfig.auth.googleOAuth.enabled};
  static const String googleClientId = '${flutterConfig.auth.googleOAuth.clientId}';
  static const String googleRedirectUri = '${flutterConfig.auth.googleOAuth.redirectUri}';
  
  // API Endpoints (for backend proxy)
  static const String createUserEndpoint = '${flutterConfig.endpoints.createUser}';
  static const String findUserEndpoint = '${flutterConfig.endpoints.findUser}';
  static const String saveRecipeEndpoint = '${flutterConfig.endpoints.saveRecipe}';
  static const String getRecipesEndpoint = '${flutterConfig.endpoints.getRecipes}';
}
`;

    fs.writeFileSync(configPath, dartConfig);
    console.log('Flutter configuration saved to:', configPath);

    expect(fs.existsSync(configPath)).toBe(true);
  });

  test('create environment configuration template', async ({ page }) => {
    const envTemplate = `# InstantDB Configuration
# Copy this file to .env and fill in your values

# InstantDB App ID (from dashboard)
INSTANTDB_APP_ID=588227b6-6022-44a9-88f3-b1c2e2cce304

# Backend Proxy URL (if using backend proxy)
BACKEND_URL=http://localhost:3000

# Google OAuth Configuration
GOOGLE_CLIENT_ID=your-google-client-id-here
GOOGLE_CLIENT_SECRET=your-google-client-secret-here
GOOGLE_REDIRECT_URI=http://localhost:8080/auth/google/callback

# InstantDB Admin Token (for backend proxy)
INSTANTDB_ADMIN_TOKEN=your-admin-token-here
`;

    const envPath = path.join(__dirname, '../.env.example');
    fs.writeFileSync(envPath, envTemplate);
    console.log('Environment template saved to:', envPath);

    expect(fs.existsSync(envPath)).toBe(true);
  });
});

