// InstantDB Configuration
// Auto-generated by Playwright configuration script
// Update these values based on your InstantDB setup

class InstantDBConfig {
  static const String appId = '588227b6-6022-44a9-88f3-b1c2e2cce304';
  static const String baseUrl = 'https://api.instantdb.com';
  static const bool useBackendProxy = true;
  
  // Backend URL - Change this to your production URL when deploying
  // Development: 'http://localhost:3000'
  // Production: 'https://chefli.vercel.app' (or your Vercel domain)
  static const String backendUrl = 'https://chefli.vercel.app';
  
  // Auth Configuration
  static const bool emailPasswordEnabled = true;
  static const bool hashPasswordOnServer = true;
  static const bool googleOAuthEnabled = true;
  static const String googleClientId = '';
  static const String googleRedirectUri = '';
  
  // API Endpoints (for backend proxy)
  static const String createUserEndpoint = '/api/users/create';
  static const String findUserEndpoint = '/api/users/find';
  static const String saveRecipeEndpoint = '/api/recipes/save';
  static const String getRecipesEndpoint = '/api/recipes/get';
}
